---
applications:
  - name: celery-beat
    instances: 1
    memory: 256M
    disk_quota: 1G
    no-route: true
    health-check-type: process
    command: celery beat --app webservices.tasks --loglevel INFO
    path: ../
    stack: cflinuxfs3
    buildpacks:
      - python_buildpack
    services:
      - fec-api-elasticsearch
      - fec-redis
      - fec-creds-dev
      - fec-s3-api
      - fec-s3-snapshot
    env:
      APP_NAME: fec | api | dev
