---
applications:
  - name: celery-worker
    instances: 6
    memory: 1G
    disk_quota: 1G
    no-route: true
    health-check-type: process
    command: celery worker --app webservices.tasks --loglevel ${LOGLEVEL:=INFO} --concurrency 3
    path: ../
    stack: cflinuxfs3
    buildpacks:
      - python_buildpack
    services:
      - fec-api-search56
      - fec-redis
      - fec-creds-prod
      - fec-s3-prod
    env:
      FEC_API_USE_PROXY: true
      FEC_API_RESTRICT_DOWNLOADS: true
      APP_NAME: fec | api | prod
      PRODUCTION: True
