---
applications:
  - name: celery-beat
    instances: 1
    memory: 500M
    disk_quota: 1G
    no-route: true
    health-check-type: process
    command: celery beat --app webservices.tasks --loglevel INFO
    path: ../
    stack: cflinuxfs3
    buildpacks:
      - python_buildpack
    services:
      - fec-api-search56
      - fec-redis
      - fec-creds-prod
      - fec-s3-prod
    env:
      FEC_API_USE_PROXY: true
      FEC_API_RESTRICT_DOWNLOADS: true
      APP_NAME: fec | api | prod
      PRODUCTION: True
