---
applications:
  - name: api
    instances: 1
    memory: 1.5G
    disk_quota: 1G
    stack: cflinuxfs3
    buildpacks:
      - python_buildpack
    path: ../
    routes:
      - route: fec-dev-api.app.cloud.gov
    services:
      - fec-api-search56
      - fec-redis
      - fec-creds-dev
      - fec-s3-dev
      - test-aws-glue-etl
    env:
      APP_NAME: fec | api | dev
